# __init__.py
from .Strategy import Strategy
from .Coreset_strategy import Coreset_Strategy
from .Random_strategy import Random_Strategy
from .Uncertainty_strategy import Uncertainty_Strategy
from .Max_entropy_strategy import Max_Entropy_Strategy
from .Bayesian_sparse_set_strategy import Bayesian_Sparse_Set_Strategy
from .CIRAL_strategy import CIRAL_Strategy
from .DFAL_strategy import DFAL_Strategy
from .Softmax_hybrid_strategy import Softmax_Hybrid_Strategy
from .BADGE_strategy import BADGE_Strategy
from .Learning_loss_strategy import Learning_Loss_Strategy
from .KMeans_Strategy import KMeans_Strategy
from .Margin_Strategy import MarginSampling_Strategy
from .Active_learning_by_learning_strategy import ActiveLearningByLearning_Strategy
from .All_data_strategy import All_Data_Strategy